#!/bin/bash

# Todo: WIP

# Exit on error
set -e

# Declare constants
readonly ARCHIVE="$(realpath "$1")" # Sanitize archive path
readonly STACK="$(realpath "$2")"   # (Same)
readonly SERVICE_NAME="$3"
readonly DOCKER_DESTINATION="$4"
readonly RESTART="$5"

readonly ARCHIVE_TMP="${HOME}/.TMP" # Should be an absolute path (avoids issues with tar)

# Graceful shutdown of containers
cd "$STACK"
# docker compose down
docker compose stop

# Create directory for restoration
mkdir -p "$ARCHIVE_TMP"

# Unpack the backup archive
tar --extract --file "$ARCHIVE" --directory "$ARCHIVE_TMP"

# Copy unpacked contents to service destination (preserving permissions and timestamps)
docker compose cp --archive "${ARCHIVE_TMP}/." "${SERVICE_NAME}:${DOCKER_DESTINATION}/"

# Cleanup
rm -rf "$ARCHIVE_TMP"

# (Optionally) restart container
if [[ "$RESTART" == "true" ]]; then

  # docker compose up --detach --remove-orphans
  docker compose start

fi
